@baseUrl = http://localhost:3000/categories
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoid2FsbFN0Iiwicm9sZSI6ImZyb250ZGVzayIsImlhdCI6MTc2ODA2MDcyOSwiZXhwIjoxNzY4MDY0MzI5fQ.7ZRxiJZdnE37u32f0LmVg86tO01nq8bMljDd_xkPX9k

### Creates a new Category

POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "legumes"
}


### Lists categorys

GET {{baseUrl}}
Authorization: Bearer {{token}}


### Reads a category

GET {{baseUrl}}/4
Authorization: Bearer {{token}}


### Updates a Category

PATCH {{baseUrl}}/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Outros"
}


### Deletes a category

DELETE  {{baseUrl}}/4
Authorization: Bearer {{token}}