@baseUrl = http://localhost:3000/categories
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoid2FsbFN0Iiwicm9sZSI6ImZyb250ZGVzayIsImlhdCI6MTc2ODA3MTg3MiwiZXhwIjoxNzY4MDc1NDcyfQ.FCgYGwpcVEkeNkZxWXlTW1O1DFjKFRXEjsICz2lHn98

### Creates a new Category

POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "legumes"
}


### Lists categorys

GET {{baseUrl}}
Authorization: Bearer {{token}}


### Reads a category

GET {{baseUrl}}/4
Authorization: Bearer {{token}}


### Updates a Category

PATCH {{baseUrl}}/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Outros"
}


### Deletes a category

DELETE  {{baseUrl}}/3
Authorization: Bearer {{token}}