@baseUrl = http://localhost:3000/categories
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoid2FsbFN0Iiwicm9sZSI6ImZyb250ZGVzayIsImlhdCI6MTc2ODI0MTAzOCwiZXhwIjoxNzY4MjQ0NjM4fQ.Py0iX8hHTkOLSwezea_Y09sEpE_YyviB-fcwqMsevTE

### Creates a new Category

POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "legumes"
}


### Lists categorys

GET {{baseUrl}}
Authorization: Bearer {{token}}


### Reads a category

GET {{baseUrl}}/5
Authorization: Bearer {{token}}


### Updates a Category

PATCH {{baseUrl}}/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Outros"
}


### Deletes a category

DELETE  {{baseUrl}}/5
Authorization: Bearer {{token}}