@baseUrl = http://localhost:3000/products
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoid2FsbFN0Iiwicm9sZSI6ImZyb250ZGVzayIsImlhdCI6MTc2ODI0Njc3NiwiZXhwIjoxNzY4MjUwMzc2fQ.iIi0Mj3j5nyZOHPmqqjnGVuHEmh5-cGhcMwKRtm7_9w


### Creates a new product

POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Laranja",
  "package": "kilo",
  "category": 1
}


### Lists products

GET {{baseUrl}}
Authorization: Bearer {{token}}


### Reads a product

GET {{baseUrl}}/3
Authorization: Bearer {{token}}


### Updates a product

PATCH {{baseUrl}}/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "package": "kilo"
}


### Deletes a product

DELETE  {{baseUrl}}/3
Authorization: Bearer {{token}}