@baseUrl = http://localhost:3000/user
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoid2FsbFN0Iiwicm9sZSI6ImZyb250ZGVzayIsImlhdCI6MTc2ODA0MjYwMiwiZXhwIjoxNzY4MDQ2MjAyfQ.ne0bxdQ9HyCdtJrg4RVycJ1ksAEXMjkaK5jlxfsoFRs

### Creates a new User

POST {{baseUrl}}
Content-Type: application/json

{
  "username": "wallSt",
  "email": "wallacycleyton@gmail.com",
  "password": "123456"
}


### Lists users

GET {{baseUrl}}
Authorization: Bearer {{token}}


### Reads a user

GET {{baseUrl}}/1
Authorization: Bearer {{token}}


### Updates a User

PATCH {{baseUrl}}/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "role": "frontdesk"
}


### Deletes a user

DELETE  {{baseUrl}}/4
Authorization: Bearer {{token}}